export const APIs = {
    // BASE_URL : 'http://localhost:3000/router',    
    BASE_URL : 'http://192.168.1.16:3000/router',    
    LOGIN_LINK : '/login',
    SIGNUP_LINK:'/signUp',
    DASHBOARD_LINK:'/getDashboardData',
    CREATE_CHALLENGE:'/createChallange',
    UPLOAD_IMAGE:'/upload',
    CHALLENGE_PRIVACY:'/privacy',
    LIKE_CHALLENGE:'/likechallenge',
    GET_ALL_COMMENTS:'/getcommentChallenge',
    COMMENT_CHALLENGE:'/commentChallenge',
    GET_USERDETAIL_BY_USERID:'/getUserDetailById',
    GET_ALL_CHALLENGE_BY_CHALLENGEID:'/getChallengeById',
    UPDATE_PROFILE:'/updateProfile',
    GET_PURPOSE_CHALLENGE:'/getPurposeChallenge',
}