export const RouterNames = {
  LOGIN_SCREEN: "loginScreen",  
  SIGNUP_SCREEN: "signupScreen",  
  VIDEO_SCREEN: 'videoScreen',
  SPLASH_SCREEN: "splashScreen",  
  CREATE_CHALLENGE_SCREEN: "createChallengeScreen",
  PROFILE_SCREEN: "profileScreen",
  UPDATE_PROFILE_SCREEN: "UpdateProfileScreen",
  EDIT_PROFILE_SCREEN: "editProfileScreen",
  HOME_SCREEN: "homeScreen",
  CHALLENGE_SCREEN: "ChallengeScreen",
  PREVIEW_CHALLENGE_SCREEN: "previewChallenge",
  CHALLENGE :"challenge",
  LOGIN :"login",
  PRIVACY :"privacy",
  FORGOT_SCREEN:'forgotPassword',
  OTP_SCREEN:'otp',
  RESET_SCREEN:'resetPassword',
  COMMENTS:'comments'
};
