export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const REGISTER_LOADING = 'REGISTER_LOADING'
export const REGISTER_CLEAR_STATE = 'REGISTER_CLEAR_STATE'